* my custom spacemacs config
基线版本来源于子龙山人的 Emacs 配置
感谢子龙山人的贡献！

以下说明来源于子龙山人的信息：

** Mac 平台推荐安装 Emacs 的方法

#+BEGIN_SRC sh
brew tap railwaycat/emacsmacport;
brew install emacs-mac --with-spacemacs-icon --HEAD --with-gnutls
#+END_SRC

注： =--with-gnutls= 是用来支持 ssl 的

** Windows 平台推荐安装 Emacs方法
1. 使用 https://sourceforge.net/projects/emacsbinw64/files/release/ 上面的 Emacs 版本，我目前使用的 Emacs 25.1

2. 安装 pt, 这样 helm-ag 也可以使用 pt 来搜索 。pt 的下载地址： https://github.com/monochromegane/the_platinum_searcher

3. 安装 ispell，用来做拼写检查。你需要下载 aspell 和 对应的 English 字典。 https://www.emacswiki.org/emacs/AspellWindows

4. 安装 SharpKeys, 把左 window 键修改成 app 键 ，把大写键修改成 Ctrl 键 。 https://sharpkeys.codeplex.com/

5. 安装 ctags： http://ctags.sourceforge.net/

** 使用方法

#+BEGIN_SRC sh
  #clone spacemacs repo and use develop branch
  git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d -b develop

  #clone zilongshanren layer and checkout develop branch
  git clone https://github.com/zilongshanren/spacemacs-private.git ~/.spacemacs.d/
#+END_SRC


** 安装 SourceCodePro 字体
下载地址：https://github.com/adobe-fonts/source-code-pro/releases

** 配置说明
1. 主要分成 5 个 layer
  - zilongshanren-ui: 定制 mode-line，font face 等配置。
  - zilongshanren-programming：和编程相关的配置。
  - zilongshanren-misc：一些杂项，不属于其它分类的都放在这里面。
  - zilongshanren-org：和 org 相关的配置
  - zilongshanren-better-defaults: 增强 Emacs 自带的 package 和功能

2. Spacemacs Rocks 系统视频演示：https://github.com/zilongshanren/Spacemacs-rocks/issues/5 , 让你从此爱上 Emacs :smile:


** 可能会遇到的问题
1. 如果使用了 =.spacemacs.d= 目录来保存你的 spacemacs 配置，就不需要在 HOME 目录维护一个 =.spacemacs= 文件了。 至于为什么要使用 =.spacemacs.d= 目录而不是 =.spacemacs= 文件，主要是方便分离自己的配置与 spacemacs 的配置，更新更容易。
2. 如果发现添加在 =.spacemacs.d/init.el= 里面的配置没有生效，检查一下是否你的 HOME 目录还存在一个 =.spacemacs= 文件。

** Happy Hacking:smile: 
